#!/usr/bin/env node
/**
 * Extract per-glyph advances from the vendored WOFF2 faces in src/fonts.css.
 * Output is checked in as src/metrics/advances.js — rerunning on unchanged
 * fonts must be byte-identical.
 */
import { createHash } from "node:crypto";
import { mkdtempSync, readFileSync, rmSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { createCanvas, GlobalFonts } from "@napi-rs/canvas";

const ROOT = join(dirname(fileURLToPath(import.meta.url)), "..");
const CSS = join(ROOT, "src/fonts.css");
const OUT = join(ROOT, "src/metrics/advances.js");
const REF = 100;

const extractFaces = (css) => {
	const faces = [];
	const re =
		/@font-face\s*\{[^}]*font-family:\s*"([^"]+)"[\s\S]*?url\("data:font\/woff2;base64,([^"]+)"\)/g;
	let m;
	while ((m = re.exec(css))) {
		faces.push({ family: m[1], bytes: Buffer.from(m[2], "base64") });
	}
	return faces;
};

const notdefWidth = (ctx) => {
	// A code point no MEGA face covers. Used as the missing-glyph advance.
	return round(ctx.measureText("\uFFFF").width);
};

const round = (n) => Math.round(Number(n) * 10000) / 10000;

const scanAdvances = (ctx, missing) => {
	const advances = {};
	for (let cp = 0x20; cp <= 0xffff; cp++) {
		if (cp >= 0xd800 && cp <= 0xdfff) continue;
		const ch = String.fromCodePoint(cp);
		const w = round(ctx.measureText(ch).width);
		if (w !== missing || cp <= 0x7e) advances[String(cp)] = w;
	}
	return advances;
};

const main = () => {
	const css = readFileSync(CSS, "utf8");
	const extracted = extractFaces(css);
	if (extracted.length < 3) {
		throw new Error(`expected ≥3 @font-face blocks in fonts.css, found ${extracted.length}`);
	}

	const dir = mkdtempSync(join(tmpdir(), "mega-press-metrics-"));
	const faces = {};
	try {
		for (const face of extracted) {
			const file = join(dir, `${face.family.replace(/\s+/g, "-")}.woff2`);
			writeFileSync(file, face.bytes);
			if (!GlobalFonts.registerFromPath(file, face.family)) {
				throw new Error(`failed to register ${face.family}`);
			}
			const canvas = createCanvas(8, 8);
			const ctx = canvas.getContext("2d");
			ctx.font = `400 ${REF}px "${face.family}"`;
			const hx = ctx.measureText("Hxdp");
			const cap = ctx.measureText("H");
			const missing = notdefWidth(ctx);
			const advances = scanAdvances(ctx, missing);
			const keys = Object.keys(advances)
				.map(Number)
				.sort((a, b) => a - b);
			const sorted = {};
			for (const k of keys) sorted[String(k)] = advances[String(k)];
			faces[face.family] = {
				sha256: createHash("sha256").update(face.bytes).digest("hex"),
				missing,
				ascent: round(hx.fontBoundingBoxAscent ?? REF * 0.8),
				descent: round(hx.fontBoundingBoxDescent ?? REF * 0.2),
				cap: round(cap.actualBoundingBoxAscent ?? REF * 0.7),
				advances: sorted,
			};
		}
	} finally {
		rmSync(dir, { recursive: true, force: true });
	}

	const table = { version: 1, refSize: REF, faces };
	const json = JSON.stringify(table, null, "\t");
	const body = `/** Baked glyph advances. Generated by scripts/bake-metrics.mjs — do not edit. */\nexport const METRICS_TABLE = ${json};\n`;
	writeFileSync(OUT, body);
	const counts = Object.entries(faces)
		.map(([n, f]) => `${n}:${Object.keys(f.advances).length}`)
		.join(" ");
	process.stdout.write(`wrote ${OUT} (${counts})\n`);
};

main();
